# Streamlit Cloud Secrets Configuration Example
# This file should be configured in the Streamlit Cloud dashboard, not committed to git

# Gemini API Configuration (required for Streamlit Cloud deployment)
# GEMINI_API_KEY = "your_gemini_api_key_here"

# Google Custom Search Configuration (optional)
# GOOGLE_API_KEY = "your_google_api_key_here"
# GOOGLE_CSE_ID = "your_custom_search_engine_id_here"